name: my_medicine_app
description: "A Flutter app for checking the authenticity of medicines using barcode scanning and providing medicine recommendation."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  http: ^1.2.1
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/medicine_database2.db
    - assets/background_image.png
    - assets/background_image2.png
